# Generated by Django 2.0.5 on 2018-07-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departmentuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
