# Generated by Django 2.0.5 on 2018-07-09 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_match_active_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.CharField(max_length=200)),
                ('question_two', models.CharField(max_length=200)),
                ('question_three', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trivia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='prediction',
            name='away_result',
            field=models.IntegerField(verbose_name='Resultado Visitante'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='home_result',
            field=models.IntegerField(verbose_name='Resultado Local'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_prediction', to='events.Match'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
