# Generated by Django 2.0.5 on 2018-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180709_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
