# Generated by Django 2.0.5 on 2018-07-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_question_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='questions',
        ),
        migrations.AddField(
            model_name='trivia',
            name='options',
            field=models.ManyToManyField(to='events.Option'),
        ),
    ]
