# Generated by Django 2.1.3 on 2021-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180709_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='options',
            field=models.ManyToManyField(related_name='pizzas', to='events.Option'),
        ),
    ]
