# Generated by Django 2.0.5 on 2018-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_question_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
