version: '3'

services:
    db:
        image: 'postgres:10.3-alpine'
        restart: always
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
    django:
        container_name: album_server
        build: .
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
        volumes:
            - /var/www/album/node_modules
            - ./backend:/var/www/album
            - ./static:/var/www/album/static
        ports:
            - "8000:8000"
        env_file:
            - ./.docker.env
        depends_on:
            - db
