# Generated by Django 2.0.4 on 2018-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.CharField(max_length=250),
        ),
    ]
