# Generated by Django 2.0.4 on 2018-05-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='wave',
            field=models.IntegerField(default=1),
        ),
    ]
