# Generated by Django 2.0.4 on 2018-05-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180520_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='order',
            new_name='order_card',
        ),
    ]
