# Generated by Django 2.0.5 on 2018-06-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_notification_receiver_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='email_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
