# Generated by Django 2.0.5 on 2018-06-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_email_redeemed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='email_redeemed',
        ),
    ]
