# Generated by Django 2.0.5 on 2018-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_card_email_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
