# Generated by Django 2.0.5 on 2018-07-09 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20180709_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='fk_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_code', to='cards.Card'),
        ),
    ]
