# Generated by Django 2.0.5 on 2018-07-09 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20180606_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='fk_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='code',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL),
        ),
    ]
