# Generated by Django 2.2 on 2022-10-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20210712_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='arrival_date',
            field=models.CharField(max_length=100),
        ),
    ]
